# Must use the dl.bintray.com to instead the packagecloud.io because there no https://packagecloud.io/rabbitmq/erlang/ubuntu
- name: add a key used to sign RabbitMQ
  apt_key:
    url: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc

- name: add the apt repository
  apt_repository:
    repo: "{{item}}"
    state: present
    filename: bintray.rabbitmq
  with_items:
    - deb https://dl.bintray.com/rabbitmq-erlang/debian bionic erlang
    - deb https://dl.bintray.com/rabbitmq/debian bionic main

- name: Install RabbitMQ
  apt:
    name: rabbitmq-server

- name: Add soft link 
  shell: |
    ln -sf /usr/lib/rabbitmq /data
    ln -sf /var/log/rabbitmq /data/logs
    ln -sf /usr/lib/erlang /data
