# Must use the dl.bintray.com to instead the packagecloud.io because there no https://packagecloud.io/rabbitmq/erlang/ubuntu
- name: add a key used to sign RabbitMQ
  apt_key:
    url: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc

- name: add the apt repository
  apt_repository:
    repo: "{{item}}"
    state: present
    filename: bintray.rabbitmq
  with_items:
    - deb https://dl.bintray.com/rabbitmq-erlang/debian bionic erlang
    - deb https://dl.bintray.com/rabbitmq/debian bionic main

- name: Install RabbitMQ and Erlang
  apt:
    name: "{{item}}"
  with_items:
    - "erlang=1:{{rabbitmq_erlang_major_version}}.*"
    - "rabbitmq-server={{rabbitmq_version}}.*"

- name: Copy Erlang and RabbitMQ version pinning file
  template:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
  with_items:
    - {src: "erlang_pinn",dest: "/etc/apt/preferences.d/erlang"}
    - {src: "rabbitmq_pinn",dest: "/etc/apt/preferences.d/rabbitmq"}
    